### ISSUE TITLE
Missing open/close commands for RTS devices

### ISSUE THREAD

**Issue by AndreasExner** [Excodibur/ioBroker.tahoma#27] opened 2021-07-18 12:40 UTC
Hi. Since a couple of day's my RTS devices only have "test" and "identify" commands. IO devices and scenes are ok. I've removed all DP, removed special characters from the names, disconnected all apps from the API and reconnected with fresh crendentials. The log shows no warning.

**Comment by Excodibur** [comment] 2021-08-06 13:46
Hi Andreas,

thanks for reporting the issue! This indeed might be a bug in the adapter itself. This topic seems to be a duplicate of https://github.com/Excodibur/ioBroker.tahoma/issues/17, so I'll close this ticket in favor of the other.

**Closed as completed by Excodibur** 2021-08-06 13:46 UTC
Labels: duplicate
